kind: pipeline
type: kubernetes
name: default

trigger:
  branch:
  - master

clone:
  disable: true

steps:
- name: trigger
  image: plugins/downstream
  settings:
    server: http://drone-github
    token:
      from_secret: drone_token
    repositories:
    - TheDrHax/BlackSilverUfa
